### ISSUE TITLE
Firefox cert error

### ISSUE THREAD

**Issue by geemang2000** [AutoGeneral/IridiumApplicationTesting#82]
Firefox fails with 
![screen shot 2017-01-10 at 5 30 34 pm](https://cloud.githubusercontent.com/assets/392233/21829217/83651ac4-d75a-11e6-8ada-96f0af57f9ee.png)

Is there a work around for using a profile or using a browser capability to accept all certs?

**Comment by mcasperson** [comment]
I believe this issue has been resolved in the firefox webdriver since 0.11.1 (which is the version currently included in Iridium). Try downloading the latest version from https://github.com/mozilla/geckodriver/releases and manually setting the webdriver.gecko.driver system property (which overrides the driver included with Iridium).

**Comment by geemang2000** [comment]
Thanks! That worked.
here is the command line I used:

`java -DappURLOverride=https://spgw-dev-admin.myhost.info -DtestSource=./FirstTimeSetup.feature -Dwebdriver.gecko.driver=./geckodriver  -DenableScenarioScreenshots=true -jar IridiumApplicationTesting.jar `
